name: "llama3_8b"
backend: "python"
max_batch_size: 32
input [
  {
    name: "system_message"
    data_type: TYPE_STRING  
    dims: [1]
  },
  {
    name: "user_message"
    data_type: TYPE_STRING  
    dims: [1]
  }
]
output [
  {
    name: "generated_text"
    data_type: TYPE_STRING  
    dims: [1]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]

dynamic_batching {
    preferred_batch_size: [2, 4, 8, 16, 32]
    max_queue_delay_microseconds: 1500000
}

parameters: {
  key: "max_output_length",
  value: {string_value: "1000"}
}
