name: "llama3_8b"
backend: "python"
max_batch_size: 2
input [
  {
    name: "system_message"
    data_type: TYPE_STRING  
    dims: [1]
  },
  {
    name: "user_message"
    data_type: TYPE_STRING  
    dims: [1]
  }
]
output [
  {
    name: "generated_text"
    data_type: TYPE_STRING  
    dims: [1]
  }
]

dynamic_batching {
    preferred_batch_size: [2]
    max_queue_delay_microseconds: 1500000
}

parameters:[ {
  key: "max_length",
  value: {string_value: "8000"}
},
{
  key: 'quantize',
  value: {string_value: "full"}
}
]

