name: "trocr"
backend: "python"
max_batch_size: 32
input [
  {
    name: "image"
    data_type: TYPE_STRING  
    dims: [1]
  }
]
output [
  {
    name: "generated_text"
    data_type: TYPE_STRING  
    dims: [1]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 1 ]
  }
]

dynamic_batching {
    preferred_batch_size: [2, 4, 8, 16, 32]
    max_queue_delay_microseconds: 200
}
